### ISSUE TITLE
Response content type should be based accept header 

### ISSUE THREAD

**Issue by zamaterian** [onyx-platform/onyx-peer-http-query#2]
The request accept header should be used to determine the content type of response.

Since request contet-type is only set when using post and put (the mime type of the request body) 

This return json: 
curl -X GET "localhost:8080/replica" -H "Content-type: application/json"
which is not correct, since content-type on request only are for put/post request body.

This return edn but should return json: 
curl -X GET "localhost:8080/replica" -H "Accept: application/json"
which is not correct.

**Comment by lbradstreet** [comment]
This is a good point. The peer query would definitely benefit from content negotiation.
